# Generated by Django 4.0.1 on 2022-01-31 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='esgitildi',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='album_songs', to='spotifyapp.album'),
        ),
    ]
